"""add_staff_shifts

Revision ID: 09a27e65f0bc
Revises: 55e89269f9f0
Create Date: 2026-07-04 21:08:37.651053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a27e65f0bc'
down_revision: Union[str, None] = '55e89269f9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('work_start', sa.Time(), nullable=True))
    op.add_column('staffs', sa.Column('work_end', sa.Time(), nullable=True))
    op.add_column('staffs', sa.Column('working_days', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'working_days')
    op.drop_column('staffs', 'work_end')
    op.drop_column('staffs', 'work_start')
    # ### end Alembic commands ###
