"""add_ux_models

Revision ID: 28dcbc8b7216
Revises: a880fe110cf7
Create Date: 2026-07-04 23:25:33.027607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dcbc8b7216'
down_revision: Union[str, None] = 'a880fe110cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'salon_id', name='_user_salon_uc')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('salon_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salon_images_id'), 'salon_images', ['id'], unique=False)
    op.drop_index(op.f('ix_appointments_active_booking'), table_name='appointments', postgresql_where="((status)::text <> ALL ((ARRAY['cancelled'::character varying, 'completed'::character varying])::text[]))")
    op.add_column('salons', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('salons', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'longitude')
    op.drop_column('salons', 'latitude')
    op.create_index(op.f('ix_appointments_active_booking'), 'appointments', [sa.literal_column("COALESCE(staff_id, '-1'::integer)"), 'start_time'], unique=True, postgresql_where="((status)::text <> ALL ((ARRAY['cancelled'::character varying, 'completed'::character varying])::text[]))")
    op.drop_index(op.f('ix_salon_images_id'), table_name='salon_images')
    op.drop_table('salon_images')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
