"""Add staff and salon working hours

Revision ID: 8f915ddd5fc7
Revises: 1f55547a02b8
Create Date: 2026-07-04 19:06:07.999057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f915ddd5fc7'
down_revision: Union[str, None] = '1f55547a02b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffs_id'), 'staffs', ['id'], unique=False)
    op.drop_constraint(op.f('appointments_staff_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'staffs', ['staff_id'], ['id'], ondelete='SET NULL')
    op.add_column('salons', sa.Column('open_time', sa.Time(), nullable=True))
    op.add_column('salons', sa.Column('close_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'close_time')
    op.drop_column('salons', 'open_time')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_staff_id_fkey'), 'appointments', 'users', ['staff_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_staffs_id'), table_name='staffs')
    op.drop_table('staffs')
    # ### end Alembic commands ###
