"""add_image_url_and_rating_to_staff

Revision ID: c18ce4bd0cf5
Revises: e687ebc225a7
Create Date: 2026-07-05 22:35:31.723586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18ce4bd0cf5'
down_revision: Union[str, None] = 'e687ebc225a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('staffs', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'rating')
    op.drop_column('staffs', 'image_url')
    # ### end Alembic commands ###
