"""add_staff_id_to_reviews

Revision ID: d5081422d7ff
Revises: c18ce4bd0cf5
Create Date: 2026-07-05 22:43:38.629873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5081422d7ff'
down_revision: Union[str, None] = 'c18ce4bd0cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'staffs', ['staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'staff_id')
    # ### end Alembic commands ###
