"""add_image_url_to_salons

Revision ID: e108a1dad0f3
Revises: 28dcbc8b7216
Create Date: 2026-07-05 21:33:27.150618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e108a1dad0f3'
down_revision: Union[str, None] = '28dcbc8b7216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'image_url')
    # ### end Alembic commands ###
